services:
    psqlbox:
        image: postgres:latest
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pw
        volumes:
            - exam66vol:/var/lib/postgresql/data

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

volumes:
    exam66vol:
        external: true




