# Generated by Django 4.2.5 on 2023-09-20 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        max_length=5, verbose_name="Licence category and subcategory"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EssayQuestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mudule", models.CharField(max_length=5)),
                ("text", models.TextField()),
                ("valid", models.BooleanField(default=True)),
                (
                    "level",
                    models.IntegerField(choices=[(1, "One"), (2, "Two"), (3, "Three")]),
                ),
                ("saving_date", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MultiChoiceQuestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Question text")),
                (
                    "module",
                    models.CharField(
                        max_length=5, verbose_name="The module this question belongs to"
                    ),
                ),
                (
                    "chapter",
                    models.CharField(
                        max_length=5,
                        verbose_name="The chapter this question belongs to",
                    ),
                ),
                ("answer", models.TextField(verbose_name="The right answer")),
                (
                    "alt_answer1",
                    models.TextField(verbose_name="The first wrong alternate answer"),
                ),
                (
                    "alt_answer2",
                    models.TextField(
                        verbose_name="The second wrong alternatate answer"
                    ),
                ),
                (
                    "alt_answer3",
                    models.TextField(verbose_name="The third wrong alternate answer"),
                ),
                (
                    "valid",
                    models.BooleanField(default=True, verbose_name="Questio validity"),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[(1, "One"), (2, "Two"), (3, "Three")],
                        verbose_name="Training level",
                    ),
                ),
                (
                    "saving_date",
                    models.DateField(auto_now=True, verbose_name="Saving date"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MCQuestionUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usage_data", models.DateField()),
                (
                    "question_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="examination.multichoicequestions",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EssayQuestionUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usage_data", models.DateField()),
                (
                    "question_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="examination.essayquestions",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EssayAnswers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.TextField(verbose_name="Essay answer")),
                (
                    "key_points",
                    models.CharField(max_length=150, verbose_name="Answer key points"),
                ),
                (
                    "question_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="examination.essayquestions",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EssayAnsToCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="examination.essayanswers",
                    ),
                ),
                (
                    "category_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="examination.categories",
                    ),
                ),
            ],
        ),
    ]
