# Generated by Django 4.2.5 on 2023-09-20 07:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("examination", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Categories",
            new_name="Category",
        ),
        migrations.RenameModel(
            old_name="EssayAnswers",
            new_name="EssayAnswer",
        ),
        migrations.RenameModel(
            old_name="EssayQuestions",
            new_name="EssayQuestion",
        ),
        migrations.RenameModel(
            old_name="MultiChoiceQuestions",
            new_name="MultiChoiceQuestion",
        ),
    ]
