# Generated by Django 4.2.5 on 2023-09-20 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("examination", "0002_rename_categories_category_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="essayquestion",
            old_name="mudule",
            new_name="module",
        ),
        migrations.RemoveField(
            model_name="essayquestionusage",
            name="usage_data",
        ),
        migrations.RemoveField(
            model_name="mcquestionusage",
            name="usage_data",
        ),
        migrations.AddField(
            model_name="essayquestionusage",
            name="usage_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                verbose_name="The date the essay question has been used",
            ),
        ),
        migrations.AddField(
            model_name="mcquestionusage",
            name="usage_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                verbose_name="The date the multichoice question has been used",
            ),
        ),
        migrations.AlterField(
            model_name="multichoicequestion",
            name="chapter",
            field=models.CharField(
                blank=True,
                max_length=5,
                verbose_name="The chapter this question belongs to",
            ),
        ),
        migrations.AlterField(
            model_name="multichoicequestion",
            name="module",
            field=models.CharField(
                blank=True,
                max_length=5,
                verbose_name="The module this question belongs to",
            ),
        ),
    ]
