# Generated by Django 4.2.5 on 2023-10-18 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "examination",
            "0003_selectedquestion_rename_group_name_chaptergroup_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="essayquestion",
            name="saving_time",
            field=models.DateTimeField(auto_now=True, verbose_name="Saving time"),
        ),
        migrations.AlterField(
            model_name="issuedexam",
            name="creation_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation time"),
        ),
        migrations.AlterField(
            model_name="issuedexam",
            name="handout_time",
            field=models.DateTimeField(
                null=True, verbose_name="The time exam is handed out"
            ),
        ),
        migrations.AlterField(
            model_name="multichoicequestion",
            name="saving_time",
            field=models.DateTimeField(auto_now=True, verbose_name="Saving time"),
        ),
        migrations.CreateModel(
            name="GivenAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer",
                    models.TextField(
                        blank=True, verbose_name="The answer given by the examinee"
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        null=True, verbose_name="Is the given answer correct?"
                    ),
                ),
                (
                    "saving_time",
                    models.DateTimeField(auto_now=True, verbose_name="Saving time"),
                ),
                (
                    "creation_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation time"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="examination.selectedquestion",
                        verbose_name="The question this answer respond to",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Examinee who takes the exam",
                    ),
                ),
            ],
            options={
                "permissions": [
                    (
                        "change_givenanswer_is_correct",
                        "Can change given answer is_correct",
                    ),
                    ("view_givenanswer_is_correct", "Can view given answer is_correct"),
                ],
            },
        ),
    ]
