# Generated by Django 4.2.5 on 2023-09-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("examination", "0003_rename_mudule_essayquestion_module_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="essayanswer",
            name="category",
            field=models.ManyToManyField(to="examination.category"),
        ),
        migrations.DeleteModel(
            name="EssayAnsToCategory",
        ),
    ]
