# Generated by Django 4.2.5 on 2024-11-25 15:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("examination", "0004_alter_essayquestion_saving_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="multichoicequestion",
            name="alt_answer3",
        ),
    ]
