# Generated by Django 4.2.5 on 2023-10-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("examination", "0004_alter_essayquestion_saving_time_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="selectedquestion",
            name="It must refer to an Essay Question exclusive or a Multichoice Question",
        ),
        migrations.RenameField(
            model_name="issuedexam",
            old_name="exam_identifier",
            new_name="exam_tag",
        ),
        migrations.RemoveField(
            model_name="multichoicequestion",
            name="alt_answer3",
        ),
        migrations.RemoveField(
            model_name="selectedquestion",
            name="alt_answer3",
        ),
        migrations.AlterField(
            model_name="licencecategory",
            name="code",
            field=models.CharField(
                max_length=5,
                unique=True,
                verbose_name="Licence category and subcategory code",
            ),
        ),
    ]
