# Generated by Django 4.2.5 on 2024-11-26 16:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("examination", "0005_remove_multichoicequestion_alt_answer3"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="selectedquestion",
            name="alt_answer3",
        ),
    ]
