# Generated by Django 4.2.5 on 2023-10-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "examination",
            "0005_remove_selectedquestion_it_must_refer_to_an_essay_question_exclusive_or_a_multichoice_question_and_m",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="selectedquestion",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("essay_ref__isnull", True),
                    ("multichoice_ref__isnull", True),
                    _connector="XOR",
                ),
                name="Refer to an Essay Question xor a Multichoice Question",
            ),
        ),
        migrations.RemoveField(
            model_name="selectedquestion",
            name="alt_answer3",
        ),
    ]
