# Generated by Django 4.2.5 on 2023-10-04 15:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("examination", "0007_alter_essayquestion_level_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="multichoicequestion",
            options={"ordering": ("-saving_date", "module", "chapter")},
        ),
    ]
