# Generated by Django 4.2.5 on 2023-10-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("examination", "0008_alter_multichoicequestion_options"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="multichoicequestion",
            constraint=models.CheckConstraint(
                check=models.Q(("module", ""), ("chapter", ""), _connector="OR"),
                name="module_or_chapter",
            ),
        ),
    ]
