# Generated by Django 4.2.5 on 2023-10-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("examination", "0009_multichoicequestion_module_or_chapter"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="multichoicequestion",
            name="module_or_chapter",
        ),
        migrations.AddConstraint(
            model_name="multichoicequestion",
            constraint=models.CheckConstraint(
                check=models.Q(("module", ""), ("chapter", ""), _connector="XOR"),
                name="module_xor_chapter",
            ),
        ),
    ]
